### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by csawye01**
Many thanks to contributing to nf-core/nanodemux!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/nanodemux branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/nanodemux)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/nanodemux/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by drpatelh** [comment]
Thanks @csawye01 ! We arent actually using `pycoQC` to QC the fastq files though so the `README` is correct?

**Comment by drpatelh** [comment]
And also PRs for any development code should be made to `dev`. `master` is reserved for release or stable code only 👍

**Comment by drpatelh** [comment]
How did you submit the PR because I didnt get an email alert? 😕

**Comment by csawye01** [comment]
They are both using the summary file generated from Guppy that is outputting the fastq files so its a bit confusing to have Nanoplot listed twice. 
Sorry about that, I thought since it was just a text edit for the README it would be fine on here but next time I'll make changes on the dev branch.

**Comment by drpatelh** [comment]
No probs! 😃 

Yeah, I didnt know how else to list it other than having a separate QC section for the sequencing and FastQ...but we would actually be running `Nanoplot` twice in the pipeline.

**Pull request closed without merging**
